In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('nba_final.csv')

In [4]:
data.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No

In [5]:
data.shape

(1408, 45)

In [6]:
data.size

63360

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        12 non-null     object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1404 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1309 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1393 non-null   float64
 19  eFG.        1404 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1361 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1346 non-null   float64
 33  mean_views  1270 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1249 non-null   float64
 40  PRank       1249 non-null   float64
 41  Mvot        1004 non-null   float64
 42  MRank       1004 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [8]:
data.Pos2.value_counts()

SG    5
SF    3
C     2
PF    2
Name: Pos2, dtype: int64

In [9]:
data['Pos2'] = data['Pos2'].replace(np.nan,'NONE')
data['Pos2'].unique()

array(['NONE', 'C', 'SG', 'SF', 'PF'], dtype=object)

In [10]:
data.Pos2.value_counts()

NONE    1396
SG         5
SF         3
C          2
PF         2
Name: Pos2, dtype: int64

In [11]:
data.isna().sum()

Rk              0
Player.x        0
Player_ID       0
Pos1            0
Pos2            0
Age             0
Tm              0
G               0
GS              0
MP              0
FG              0
FGA             0
FG.             4
X3P             0
X3PA            0
X3P.           99
X2P             0
X2PA            0
X2P.           15
eFG.            4
FT              0
FTA             0
FT.            47
ORB             0
DRB             0
TRB             0
AST             0
STL             0
BLK             0
TOV             0
PF              0
PTS             0
Salary         62
mean_views    138
Season          0
Conference      0
Role            0
Fvot            0
FRank           0
Pvot          159
PRank         159
Mvot          404
MRank         404
Score           0
Play            0
dtype: int64

In [12]:
data = data.fillna(0)

In [13]:
data.isna().sum()

Rk            0
Player.x      0
Player_ID     0
Pos1          0
Pos2          0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG.           0
X3P           0
X3PA          0
X3P.          0
X2P           0
X2PA          0
X2P.          0
eFG.          0
FT            0
FTA           0
FT.           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Salary        0
mean_views    0
Season        0
Conference    0
Role          0
Fvot          0
FRank         0
Pvot          0
PRank         0
Mvot          0
MRank         0
Score         0
Play          0
dtype: int64

In [14]:
data.head(10).T

,0,1,2,3,4,5,6,7,8,9
Rk,170,58,157,352,10,203,221,12,464,65
Player.x,A.J. Hammons,Aaron Brooks,Aaron Gordon,Adreian Payne,Al-Farouq Aminu,Al Horford,Al Jefferson,Alan Anderson,Alan Williams,Alec Burks
Player_ID,hammoaj01,brookaa01,gordoaa01,paynead01,aminual01,horfoal01,jeffeal01,anderal01,willial03,burksal01
Pos1,C,PG,SF,PF,PF,C,C,SF,C,SG
Pos2,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
Age,24,32,21,25,26,30,32,34,24,25
Tm,DAL,IND,ORL,MIN,POR,BOS,IND,LAC,PHO,UTA
G,22,65,80,18,61,68,66,30,47,42
GS,0,0,72,0,25,68,1,0,0,0
MP,7.4,13.8,28.7,7.5,29.1,32.3,14.1,10.3,15.1,15.5
FG,0.8,1.9,4.9,1.3,3.0,5.6,3.6,1.0,2.9,2.4
FGA,1.9,4.6,10.8,3.0,7.6,11.8,7.1,2.7,5.7,5.9
FG.,0.405,0.403,0.454,0.426,0.393,0.473,0.499,0.375,0.517,0.399
X3P,0.2,0.7,1.0,0.2,1.1,1.3,0.0,0.5,0.0,0.6
X3PA,0.5,2.0,3.3,0.8,3.5,3.6,0.0,1.5,0.0,1.8
X3P.,0.5,0.375,0.288,0.2,0.33,0.355,0.0,0.318,0.0,0.329
X2P,0.5,1.1,4.0,1.1,1.9,4.3,3.6,0.5,2.9,1.8
X2PA,1.5,2.6,7.5,2.2,4.2,8.2,7.1,1.2,5.7,4.1
X2P.,0.375,0.424,0.528,0.513,0.445,0.524,0.5,0.444,0.519,0.43
eFG.,0.464,0.483,0.499,0.454,0.468,0.527,0.499,0.463,0.517,0.45
FT,0.4,0.5,2.0,0.8,1.6,1.6,1.0,0.4,1.5,1.4
FTA,0.9,0.6,2.7,1.1,2.2,2.0,1.3,0.5,2.4,1.9
FT.,0.45,0.8,0.719,0.737,0.706,0.8,0.765,0.75,0.625,0.769
ORB,0.4,0.3,1.5,0.5,1.3,1.4,1.1,0.1,2.0,0.4
DRB,1.3,0.8,3.6,1.3,6.1,5.4,3.1,0.7,4.2,2.5
TRB,1.6,1.1,5.1,1.8,7.4,6.8,4.2,0.8,6.2,2.9
AST,0.2,1.9,1.9,0.4,1.6,5.0,0.9,0.4,0.5,0.7
STL,0.0,0.4,0.8,0.4,1.0,0.8,0.3,0.1,0.6,0.4
BLK,0.6,0.1,0.5,0.4,0.7,1.3,0.2,0.0,0.7,0.1
TOV,0.5,1.0,1.1,0.4,1.5,1.7,0.5,0.2,0.8,0.8
PF,1.0,1.4,2.2,1.8,1.7,2.0,1.9,1.2,2.7,1.2
PTS,2.2,5.0,12.7,3.5,8.7,14.0,8.1,2.9,7.4,6.7
Salary,0.0,2700000.0,4351320.0,2022240.0,7680965.0,26540100.0,10230179.0,1315448.0,874636.0,9904495.0
mean_views,3.32,11.155738,1713.986339,205.855191,604.34153,1556.382514,603.188525,5.409341,21.213115,122.505464
Season,2016-17,2016-17,2016-17,2016-17,2016-17,2016-17,2016-17,2016-17,2016-17,2016-17
Conference,West,Est,Est,West,West,Est,Est,West,West,West
Role,Front,Back,Front,Front,Front,Front,Front,Front,Front,Back
Fvot,786,2474,22774,861,4971,12219,2936,3096,607,1981
FRank,123,64,29,120,69,14,84,88,127,72
Pvot,0.0,0.0,0.0,1.0,7.0,8.0,1.0,1.0,0.0,0.0
PRank,0.0,0.0,0.0,52.0,23.0,16.0,60.0,52.0,0.0,0.0
Mvot,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
MRank,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
Score,83.5,48.2,40.0,75.5,42.8,12.5,60.0,59.5,85.5,53.0
Play,No,No,No,No,No,No,No,No,No,No

In [15]:
data = data.drop(['Player.x','Player_ID'],axis = 1)

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data['Pos1'] = le.fit_transform(data['Pos1'])

data['Pos2'] = le.fit_transform(data['Pos2'])

data['Tm'] = le.fit_transform(data['Tm'])

data['Season'] = le.fit_transform(data['Season'])

data['Conference'] = le.fit_transform(data['Conference'])

data['Role'] = le.fit_transform(data['Role'])

data['Play'] = le.fit_transform(data['Play'])

In [17]:
data.head()

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,0,1,24,6,22,0,7.4,0.8,1.9,...,1,1,786,123,0.0,0.0,0.0,0.0,83.5,0
1,58,2,1,32,11,65,0,13.8,1.9,4.6,...,0,0,2474,64,0.0,0.0,0.0,0.0,48.2,0
2,157,3,1,21,21,80,72,28.7,4.9,10.8,...,0,1,22774,29,0.0,0.0,0.0,0.0,40.0,0
3,352,1,1,25,17,18,0,7.5,1.3,3.0,...,1,1,861,120,1.0,52.0,0.0,0.0,75.5,0
4,10,1,1,26,24,61,25,29.1,3.0,7.6,...,1,1,4971,69,7.0,23.0,0.0,0.0,42.8,0

In [18]:
features = data.drop(['Play'],axis = 1)

In [19]:
X= data.drop(['Play'],axis = 1)
y = data['Play']

In [20]:
#standardize

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x = sc.fit_transform(X)

In [21]:
x

array([[-0.58191469, -1.40108842, -0.07184075, ..., -0.16623906,
        -1.46817686,  0.19138945],
       [-1.32505241, -0.01428174, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.66146791],
       [-0.66817174,  0.67912159, -0.07184075, ..., -0.16623906,
        -1.46817686, -0.85958209],
       ...,
       [ 0.33373715,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.36799438],
       [ 0.8977256 , -1.40108842, -0.07184075, ..., -0.16623906,
         0.54775392, -0.13960618],
       [ 1.32237572,  1.37252493, -0.07184075, ..., -0.16623906,
         0.83574403,  1.09256735]])

In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state = 29)

In [23]:
x_train.shape

(985, 42)

In [24]:
#building a non pca model 
#logistic regression

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train,y_train)
lr_pred = lr.predict(x_test)

from sklearn.metrics import classification_report

cr = classification_report(lr_pred,y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       408
           1       0.74      0.93      0.82        15

    accuracy                           0.99       423
   macro avg       0.87      0.96      0.91       423
weighted avg       0.99      0.99      0.99       423

In [25]:
cr = classification_report(lr.predict(x_train),y_train)
print(cr)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       934
           1       0.85      0.90      0.88        51

    accuracy                           0.99       985
   macro avg       0.92      0.95      0.93       985
weighted avg       0.99      0.99      0.99       985

In [26]:
#PCA 
from sklearn.decomposition import PCA

p = PCA(n_components=42)
pca_data = p.fit_transform(x)

In [27]:
x.shape

(1408, 42)

In [28]:
pca_data.shape

(1408, 42)

In [29]:
p.explained_variance_ratio_

array([3.75174682e-01, 1.13182629e-01, 6.35751445e-02, 5.90223744e-02,
       4.68046673e-02, 3.17258286e-02, 3.04672253e-02, 2.57752916e-02,
       2.37741420e-02, 2.34192939e-02, 2.00822745e-02, 1.87211978e-02,
       1.81548208e-02, 1.61312276e-02, 1.48820659e-02, 1.32701762e-02,
       1.13209751e-02, 1.09680103e-02, 1.00734420e-02, 8.74517961e-03,
       8.48423472e-03, 7.63845153e-03, 7.05079363e-03, 6.66632868e-03,
       6.31889814e-03, 6.05786468e-03, 4.95383225e-03, 4.39065121e-03,
       4.07555276e-03, 2.80782752e-03, 1.87900251e-03, 1.27838451e-03,
       1.07622058e-03, 9.62117718e-04, 4.02532234e-04, 3.17289461e-04,
       1.91096807e-04, 1.63003187e-04, 6.45690974e-06, 5.32680015e-06,
       2.12261400e-06, 1.36293338e-06])

In [30]:
len(p.explained_variance_ratio_)

42

In [31]:
p.explained_variance_ratio_.cumsum()*100

array([ 37.51746824,  48.83573112,  55.19324557,  61.09548301,
        65.77594975,  68.94853261,  71.99525514,  74.5727843 ,
        76.95019849,  79.29212788,  81.30035533,  83.17247511,
        84.98795719,  86.60107995,  88.08928653,  89.41630416,
        90.54840166,  91.6452027 ,  92.6525469 ,  93.52706486,
        94.37548833,  95.13933349,  95.84441285,  96.51104572,
        97.14293553,  97.748722  ,  98.24410522,  98.68317035,
        99.09072562,  99.37150837,  99.55940862,  99.68724708,
        99.79486913,  99.89108091,  99.93133413,  99.96306307,
        99.98217276,  99.99847307,  99.99911877,  99.99965145,
        99.99986371, 100.        ])

In [32]:

p = PCA(n_components=16)
pca_data = p.fit_transform(x)

In [33]:
x.shape

(1408, 42)

In [34]:
pca_data.shape

(1408, 16)

In [35]:
p.explained_variance_ratio_*100

array([37.51746824, 11.31826287,  6.35751445,  5.90223744,  4.68046673,
        3.17258207,  3.04672241,  2.57752901,  2.37741028,  2.34192931,
        2.00822635,  1.87211612,  1.8154761 ,  1.61311445,  1.48805693,
        1.3265467 ])

In [36]:
p.explained_variance_ratio_.sum()*100

89.41565945553674

In [37]:
data.head()

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,0,1,24,6,22,0,7.4,0.8,1.9,...,1,1,786,123,0.0,0.0,0.0,0.0,83.5,0
1,58,2,1,32,11,65,0,13.8,1.9,4.6,...,0,0,2474,64,0.0,0.0,0.0,0.0,48.2,0
2,157,3,1,21,21,80,72,28.7,4.9,10.8,...,0,1,22774,29,0.0,0.0,0.0,0.0,40.0,0
3,352,1,1,25,17,18,0,7.5,1.3,3.0,...,1,1,861,120,1.0,52.0,0.0,0.0,75.5,0
4,10,1,1,26,24,61,25,29.1,3.0,7.6,...,1,1,4971,69,7.0,23.0,0.0,0.0,42.8,0

In [38]:
pd.DataFrame(pca_data)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-4.221712,0.403962,2.101096,-1.923919,0.350723,-0.085433,-0.263900,-1.622057,-0.402861,0.400766,0.247927,1.939978,-0.562656,0.296734,1.728953,1.002209
1,-2.049839,-1.998276,0.548774,-2.844773,0.802615,-0.713115,-0.755417,0.417743,0.622513,-0.253567,-0.758117,-0.411816,0.539281,-0.410502,0.807180,0.516618
2,2.842995,0.246162,-0.169564,-2.474008,-0.892836,0.742822,-0.053285,-1.359221,0.450497,0.046824,0.555379,-0.288924,0.865948,0.154961,-1.190845,0.087043
3,-3.555854,0.908922,1.453616,-1.249618,0.259071,0.212124,0.579232,-0.509858,-1.087474,1.039513,-0.623443,0.323490,-1.111708,-0.479174,-0.401699,0.085736
4,1.492529,0.738593,0.483122,-2.014073,-1.037800,-1.743119,0.845930,-1.892733,-0.577925,-0.055541,0.149170,0.232518,0.133269,-0.832803,0.274639,0.693599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,-0.889306,2.373146,-0.756435,0.791886,0.000906,-0.434015,1.253051,-1.544270,0.173095,-0.508424,-0.413115,-0.913746,-0.340137,0.749503,0.491872,1.112489
1404,7.393132,-2.320154,-0.832561,1.500322,-1.180354,1.949547,-0.684657,1.138117,1.250331,-0.480282,-0.997982,1.416229,0.417471,0.904894,-0.207930,-0.339979
1405,-7.128921,-3.729131,4.501673,2.666464,-5.791381,-0.713195,-0.867942,0.609859,0.091320,-0.742902,1.969960,0.220463,0.903550,-0.771799,0.091093,-0.880024
1406,-1.784659,2.023183,0.721049,0.279118,-0.592947,-1.209849,-1.561053,1.973662,-0.012817,0.038793,-0.566024,-1.665514,-0.551295,0.574661,0.030091,0.217943
1407,-2.562609,-1.364141,-0.530848,2.135463,-0.235682,2.150368,0.198425,-0.289928,-0.143029,0.546267,0.105607,-0.362657,0.982509,0.357400,0.168137,-0.102939

In [39]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(pca_data, y,test_size = 0.3,random_state = 29)

In [40]:
x_train.shape

(985, 16)

In [41]:
#logistic regression

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)
lr_pred = lr.predict(x_test)

In [42]:
from sklearn.metrics import classification_report

cr = classification_report(lr_pred,y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       406
           1       0.84      0.94      0.89        17

    accuracy                           0.99       423
   macro avg       0.92      0.97      0.94       423
weighted avg       0.99      0.99      0.99       423

In [43]:
#decision tree classifier

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

In [44]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [45]:
dt_pred = dt.predict(x_test)

In [46]:
cr_dt = classification_report(dt_pred,y_test)

In [47]:
print(cr_dt)

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       406
           1       0.58      0.65      0.61        17

    accuracy                           0.97       423
   macro avg       0.78      0.81      0.80       423
weighted avg       0.97      0.97      0.97       423

In [48]:
#random forest classifier

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

In [49]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [50]:
pred_rf = rf.predict(x_test)

In [51]:
cr_rf = classification_report(pred_rf,y_test)

In [52]:
print(cr_rf)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       409
           1       0.68      0.93      0.79        14

    accuracy                           0.98       423
   macro avg       0.84      0.96      0.89       423
weighted avg       0.99      0.98      0.98       423

In [53]:
cols = ['PC1','PC2','PC3','PC4','PC5','PC6','PC7']

pc1 = pd.DataFrame(np.round(p.components_.T[:,0:7],2),index = features.columns,columns = cols)
pc1

             PC1   PC2   PC3   PC4   PC5   PC6   PC7
Rk         -0.02  0.02 -0.04  0.10 -0.05  0.37 -0.16
Pos1       -0.01 -0.34 -0.10  0.01  0.02  0.11  0.11
Pos2        0.00 -0.02 -0.03  0.04 -0.01 -0.19  0.16
Age         0.03 -0.04 -0.03 -0.05  0.17 -0.58 -0.11
Tm          0.00  0.03 -0.02 -0.01 -0.03 -0.03  0.64
G           0.15  0.01 -0.24 -0.15  0.02 -0.10 -0.04
GS          0.20  0.01 -0.10 -0.04 -0.13 -0.06 -0.01
MP          0.23 -0.04 -0.18 -0.03 -0.10 -0.04 -0.02
FG          0.24 -0.02 -0.04  0.04 -0.04  0.08  0.02
FGA         0.24 -0.09 -0.05  0.05 -0.08  0.06 -0.00
FG.         0.08  0.28 -0.17 -0.07  0.39  0.19  0.09
X3P         0.15 -0.27 -0.18  0.07  0.09 -0.13 -0.11
X3PA        0.15 -0.28 -0.17  0.08  0.05 -0.13 -0.11
X3P.        0.06 -0.21 -0.25  0.02  0.21  0.04 -0.08
X2P         0.23  0.09  0.03  0.02 -0.08  0.16  0.07
X2PA        0.23  0.04  0.03  0.02 -0.14  0.16  0.06
X2P.        0.07  0.22 -0.17 -0.03  0.37  0.12  0.05
eFG.        0.07  0.16 -0.27 -0.04  0.49  0.13  0.04
FT          0.22 -0.03  0.09  0.07 -0.04  0.09  0.04
FTA         0.22  0.01  0.10  0.07 -0.05  0.10  0.04
FT.         0.09 -0.11 -0.20 -0.08  0.11 -0.07 -0.06
ORB         0.12  0.35  0.01 -0.04 -0.13 -0.03 -0.03
DRB         0.20  0.20 -0.01  0.01 -0.10 -0.11 -0.09
TRB         0.19  0.26 -0.00 -0.00 -0.12 -0.09 -0.08
AST         0.18 -0.16  0.01  0.05 -0.05  0.09  0.07
STL         0.18 -0.08 -0.08  0.01 -0.11  0.02  0.09
BLK         0.13  0.27  0.02 -0.01 -0.06 -0.04 -0.02
TOV         0.22 -0.06  0.03  0.05 -0.11  0.10  0.06
PF          0.17  0.14 -0.18 -0.02 -0.13 -0.05 -0.00
PTS         0.24 -0.06 -0.03  0.05 -0.02  0.06  0.01
Salary      0.17  0.01  0.07  0.07  0.02 -0.30 -0.05
mean_views  0.13 -0.05  0.26  0.13  0.23 -0.11 -0.06
Season     -0.01  0.02 -0.16  0.52 -0.02 -0.04  0.03
Conference  0.00  0.02  0.01  0.01  0.04 -0.24  0.62
Role       -0.00  0.33  0.06  0.04 -0.02 -0.22 -0.16
Fvot        0.15 -0.04  0.32  0.18  0.23 -0.03 -0.00
FRank      -0.18  0.06  0.02  0.11 -0.02  0.10  0.02
Pvot        0.16 -0.03  0.35  0.15  0.22  0.02 -0.01
PRank      -0.13  0.09 -0.15  0.37 -0.01 -0.04 -0.05
Mvot        0.13 -0.04  0.36  0.16  0.25  0.04 -0.02
MRank      -0.03  0.08 -0.21  0.51 -0.08 -0.06  0.03
Score      -0.17  0.08 -0.10  0.37 -0.02  0.04  0.01